"""add username to user model

Revision ID: 25ff494e615d
Revises: 0c8043814180
Create Date: 2024-01-16 22:09:17.077954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ff494e615d'
down_revision: Union[str, None] = '0c8043814180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_users', 'username')
    # ### end Alembic commands ###
