"""Roles, Many To Many User roles

Revision ID: b16e97236af3
Revises: 25ff494e615d
Create Date: 2024-01-17 11:40:35.428128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16e97236af3'
down_revision: Union[str, None] = '25ff494e615d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
