"""Create a baseline migrations

Revision ID: c5684b187e2f
Revises: ec2e63d139cf
Create Date: 2024-01-13 17:23:09.988519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5684b187e2f'
down_revision: Union[str, None] = 'ec2e63d139cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_posts', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_posts', 'likes')
    # ### end Alembic commands ###
